class BaseConfig(object):
    RESULT_PATH = ''
    LUC_NET_DATA_PATH = 'D://OneDrive//JustDo//The_Greening_of_YR_from_the_Perspective_of_Network//Data//LUCNetData//'
    LUC_NET_DATA_HEAD = 'InfoForLUCNet'
    LUC_NET_DATA_TAIL = '.csv'
    GEO_AGENT_PATH = 'E://MY PROGRAM//YR_Greening_Network//data//GeoAgent//'
    COUPLED_NET_DATA_PATH = 'E://MY PROGRAM//YR_Greening_Network//data//SampleData//'
    COUPLED_NET_DATA_HEAD = 'YR_GA_Info_'
    COUPLED_NET_DATA_TAIL = '.csv'
    OUT_PATH = 'D://OneDrive//JustDo//The_Greening_of_YR_from_the_Perspective_of_Network//OutPut//'
